version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '11:00'
    timezone: Japan
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
    - ">= 14.a, < 15"
  commit-message:
    prefix: deps

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "CI/CD"
  commit-message:
    prefix: ci

- package-ecosystem: pip
  directory: "models"
  schedule:
    interval: daily
    time: '11:00'
    timezone: Japan
  labels:
  - dependencies
  commit-message:
    prefix: deps

- package-ecosystem: pip
  directory: "models/fasttext"
  schedule:
    interval: daily
    time: '11:00'
    timezone: Japan
  labels:
  - dependencies
  commit-message:
    prefix: deps
