name: 'Model Image CI'

on:
  workflow_dispatch:
  schedule:
    - cron: '22 22 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/model-image.yml'
      - 'models/**'
      - '!*.md'
  pull_request:
    paths:
      - '.github/workflows/model-image.yml'
      - 'models/**'
      - '!*.md'

jobs:
  skipci:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "[skip ci] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"

  model-image-test:
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    defaults:
      run:
        working-directory: models
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Login to Packages
        run: echo '${{ secrets.GITHUB_TOKEN }}' | docker login 'docker.pkg.github.com' -u 'peaceiris' --password-stdin
      # - run: docker-compose pull --quiet
      #   if: github.event_name == 'pull_request'
      - run: make build
      - run: docker images
      # - run: make all
      # - run: docker-compose push
      #   if: github.ref == 'refs/heads/main'
