name: 'Test'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'models/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'models/**'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - run: npm i -g npm

      - name: Dump version
        run: |
          node -v
          npm --version
          git --version

      - run: npm ci
      - run: npm run fmt:check
      - run: npm run lint
      - run: npm test
      - run: npm run build

      - name: Upload test coverage as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

      - uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
