version: '3'

services:
  dev:
    build: .
    image: docker.pkg.github.com/peaceiris/actions-suggest-related-links/asrl-model-dev:latest
    container_name: asrl_model_dev
    volumes:
      - ${PWD}:/src
    stdin_open: true
    tty: true
    command:
      - bash
